
import "./globals.css";
import Header from "./components/Header";
import ReduxProvider from "./redux/ReduxProvider";


export const metadata = {
  title: "NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="bg-gray-100">
        <ReduxProvider>
          <Header />
          <main className="container mx-auto mt-8">{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
}